---
title: "babette: BEAUti 2, BEAST2 and Tracer for R"
author: "Richèl J.C. Bilderbeek"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{babette: BEAUti 2, BEAST2 and Tracer for R}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r create_files, include = FALSE}
file.copy(babette::get_babette_path("anthus_aco_sub.fas"), "test_output_0.fas")
file.copy(babette::get_babette_path("anthus_aco_sub.fas"), "my_fasta.fas")
file.copy(babette::get_babette_path("anthus_aco_sub.fas"), "my_alignment.fas")
file.copy(babette::get_babette_path("anthus_aco_sub.fas"), "anthus_aco.fas")
file.copy(babette::get_babette_path("anthus_nd2_sub.fas"), "anthus_nd2.fas")
```

This vignette does the same as the code in 
the [bioRxiv article](https://doi.org/10.1101/271866).

```{r setup}
library(babette)
mcmc <- create_test_mcmc()
```

Use a null value for `out`:

```{r}
out <- NA
```

```{r simplest_run}
if (is_beast2_installed()) {
  out <- bbt_run(
    fasta_filename = "anthus_aco.fas", 
    mcmc = mcmc
  )
}
```


```{r run_with_different_site_clock_and_tree_models}
if (is_beast2_installed()) {
  out <- bbt_run(
    "anthus_aco.fas",
    site_model = create_hky_site_model(),
    clock_model = create_rln_clock_model(),
    tree_prior = create_bd_tree_prior(),
    mcmc = mcmc
  )
}
```


```{r}
# Currently, support for multiple alignments has been deprecated
```

```{r run_with_distr}
if (is_beast2_installed()) {
  out <- bbt_run(
    "anthus_aco.fas",
    tree_prior = create_yule_tree_prior(
      birth_rate_distr = create_exp_distr()    
    ),
    mcmc = mcmc
  )
}
```

```{r run_with_distr_with_mean}
if (is_beast2_installed()) {
  out <- bbt_run(
    "anthus_aco.fas",
    tree_prior = create_yule_tree_prior(
      birth_rate_distr = create_exp_distr(
        mean = 1.0
      )    
    ),
    mcmc = mcmc
  )
}
```

```
# Deprecated
out <- bbt_run(
  "anthus_aco.fas",
  posterior_crown_age = 15,
  mcmc = mcmc
)
```

```{r run_with_crown_age}
if (is_beast2_installed()) {
  out <- bbt_run(
    "anthus_aco.fas",
    mrca_prior = create_mrca_prior(
      alignment_id = get_alignment_id("anthus_aco.fas"),
      taxa_names = get_taxa_names("anthus_aco.fas"),
      mrca_distr = create_normal_distr(
        mean = 15.0,
        sigma = 0.01
      )
    ),
    mcmc = mcmc,
    overwrite = TRUE
  )
}
```

```{r add_fake_output_if_beast2_was_not_installed}
if (is_one_na(out)) {
  out <- get_bbt_run_test_output()
}
```

```{r remove_the_traces}
traces <- remove_burn_ins(
  traces = out$estimates, 
  burn_in_fraction = 0.2
)
```


```{r}
esses <- calc_esses(
  traces = traces, 
  sample_interval = 1000
)
```

```{r}
sum_stats <- calc_summary_stats(
  traces = traces, 
  sample_interval = 1000
)
```


```{r}
plot_densitree(phylos = out$anthus_aco_trees)
```

```{r cleanup, include = FALSE}
file.remove("test_output_0.fas")
file.remove("my_fasta.fas")
file.remove("my_alignment.fas")
file.remove("anthus_aco.fas")
file.remove("anthus_nd2.fas")
```
