#!/bin/bash
#
# Usage
#
# ./babette/scripts/merge

for folder in beautier beastier tracerer mauricer babette lumier
do

  cd $folder

  echo "git folder: "$folder
  git checkout master
  git pull
  git checkout develop
  git pull
  git checkout richel
  git pull

  git checkout master
  git merge develop
  git push

  git checkout develop
  git merge richel
  git push
  cd ..
done
