#!/bin/bash

# Push all GitHubs under babette

cd ..
git add --all :/
git commit -m "babette update"
git push
cd ..

cd beautier
git add --all :/
git commit -m "babette update"
git push
cd ..

cd beastier
git add --all :/
git commit -m "babette update"
git push
cd ..

cd tracerer
git add --all :/
git commit -m "babette update"
git push
cd ..
