#!/bin/bash
# Push babette and all dependencies
#
# Usage:
#
# ./babette/scripts/push
#
#

for package in beautier tracerer beastier mauricer babette
do
  cd $package
  git add --all :/
  git commit -m "Move 'pics' to 'man/figures', fix https://github.com/ropensci/babette/issues/80"
  git push
  cd ..
done

