on:
  push:
  pull_request:

name: build_singularity

jobs:
  build_singularity:

    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        singularity_version:
          - '3.7.4'
    container:
      image: quay.io/singularity/singularity:v${{ matrix.singularity_version }}
      options: --privileged

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - name: Show singularity version
        run: singularity version

      - name: Build container
        run: ./scripts/build_singularity_container.sh

      - name: Test container, must detect PLINKs
        run: singularity test babette.sif

      - name: Show help of container
        run: singularity run-help babette.sif

      - name: Run container
        run: cat scripts/demo_container.R | ./babette.sif 

